# Generated by Django 4.1.4 on 2022-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='municipio',
            field=models.CharField(blank=True, choices=[('BE', 'Belas'), ('LU', 'Luanda'), ('CA', 'Cacuaco'), ('IC', 'Icolo e Bengo'), ('VI', 'Viana'), ('KI', 'Kilamba Kiaxi'), ('QU', 'Quissama')], max_length=50, verbose_name='Município'),
        ),
    ]
