# Generated by Django 4.1.4 on 2022-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0004_alter_actividade_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/fotos/%Y'),
        ),
    ]
