# Generated by Django 4.1.4 on 2023-10-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0006_gruporubrica_rubricaentrada_rubricasaida_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividade',
            name='local',
        ),
        migrations.AlterField(
            model_name='aquisicao',
            name='quemadquiriu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao'),
        ),
    ]
