# Generated by Django 4.2.5 on 2025-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0010_irmao_batizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefonewhatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone do Whatsapp'),
        ),
    ]
