# Generated by Django 4.2.5 on 2025-11-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0011_pessoa_telefonewhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmao',
            name='igreja',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='igreja', to='sitetibl.sitio'),
        ),
        migrations.AlterField(
            model_name='irmao',
            name='celula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celula', to='sitetibl.sitio'),
        ),
    ]
