# Generated by Django 4.2.5 on 2025-12-02 17:53

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0013_rename_igreja_irmao_localcongregacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioSemanalCelula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_celula', models.CharField(max_length=50)),
                ('lider_responsavel', models.CharField(max_length=50)),
                ('local_reuniao', models.CharField(max_length=50)),
                ('numero_participantes_membros', models.IntegerField()),
                ('numero_participantes_visitantes', models.IntegerField()),
                ('numero_participantes_criancas', models.IntegerField()),
                ('moemntos_realizados', multiselectfield.db.fields.MultiSelectField(choices=[('louvor', 'Louvor'), ('oração', 'Oração'), ('louvor', 'Louvor'), ('momento da palavra', 'Momento Da Palavra'), ('partilha de testemunhos', 'Partilha De Testemunhos'), ('intercessão', 'Intercessão'), ('tempo de comunhão', 'Tempo de Comunhão')], max_length=50)),
                ('tema_palavra', models.CharField(max_length=50)),
                ('versiculo_chave', models.CharField(max_length=50)),
                ('resumo_mensagem', models.TextField()),
                ('topicos_de_oracao', models.TextField()),
                ('alvos_e_accoes_para_proxima_semana', models.TextField()),
                ('observacoes_e_necessidades', models.TextField()),
                ('assinatura_lider', models.CharField(max_length=100)),
                ('data_reuniao', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='irmao',
            name='localcongregacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='igreja', to='sitetibl.sitio', verbose_name='Local de Congregação'),
        ),
    ]
