# Generated by Django 4.2.5 on 2025-12-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0014_relatoriosemanalcelula_alter_irmao_localcongregacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriosemanalcelula',
            old_name='moemntos_realizados',
            new_name='moementos_realizados',
        ),
    ]
