# Generated by Django 4.2.5 on 2025-12-06 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0018_alter_relatoriosemanalcelula_momentos_realizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('projecto', models.CharField(max_length=100)),
                ('montante', models.IntegerField()),
                ('centro_custo', models.CharField(choices=[('custo1', 'Custo1'), ('custo2', 'Custo2')], max_length=100)),
                ('tipificacao_custo', models.CharField(choices=[('tipificacacusto1', 'Tipificacaocusto1'), ('tipificacaocusto2', 'Tipificacaocusto2')], max_length=100)),
                ('iban', models.CharField(max_length=50)),
                ('justificativa_custo', models.TextField()),
                ('documento_justificativo', models.FileField(blank=True, upload_to='')),
                ('status_de_aprovacao', models.BooleanField(default=False)),
                ('requerente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
            ],
        ),
    ]
