# Generated by Django 4.2.5 on 2025-12-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0019_pedidosaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosaida',
            name='area',
            field=models.CharField(choices=[('departamento de musica', 'Departamento de Musica'), ('departamento de Missões', 'Departamento de Missões')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='tipificacao_custo',
            field=models.CharField(choices=[('despesas com reuniões', 'Despesas com Reunioes'), ('despesas com vistos', 'Despesas com Vistos')], max_length=100),
        ),
    ]
