# Generated by Django 4.2.5 on 2025-12-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0022_alter_pedidosaida_status_de_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosemanalcelula',
            name='lider_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao'),
        ),
    ]
