# Generated by Django 4.2.5 on 2025-12-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0025_remove_relatoriosemanalcelula_momentos_realizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='lider_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider_departamento', to='sitetibl.irmao'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='integrantes_departamento', through='sitetibl.Mandato', to='sitetibl.irmao'),
        ),
    ]
