# Generated by Django 4.2.5 on 2025-12-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0027_remove_pedidosaida_area_pedidosaida_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200)),
            ],
        ),
    ]
