# Generated by Django 4.2.5 on 2025-12-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0033_alter_relatoriosemanalcelula_nome_celula'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriosemanalcelula',
            name='nome_celula1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipo_celula'),
        ),
    ]
