# Generated by Django 4.2.5 on 2025-12-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0035_remove_relatoriosemanalcelula_nome_celula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriosemanalcelula',
            old_name='nome_celula1',
            new_name='nome_celula',
        ),
    ]
