# Generated by Django 4.2.5 on 2025-12-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0036_rename_nome_celula1_relatoriosemanalcelula_nome_celula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipificacao_Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200)),
            ],
        ),
    ]
