# Generated by Django 4.2.5 on 2025-12-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0037_centro_custo_status_aprovacao_tipificacao_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaida',
            name='centro_custo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.centro_custo'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='status_de_aprovacao1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.status_aprovacao'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='tipificacao_custo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipificacao_custo'),
        ),
    ]
