# Generated by Django 4.2.5 on 2025-12-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0039_remove_pedidosaida_centro_custo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosaida',
            old_name='centro_custo1',
            new_name='centro_custo',
        ),
        migrations.RenameField(
            model_name='pedidosaida',
            old_name='status_de_aprovacao1',
            new_name='status_de_aprovacao',
        ),
        migrations.RenameField(
            model_name='pedidosaida',
            old_name='tipificacao_custo1',
            new_name='tipificacao_custo',
        ),
    ]
