# Generated by Django 4.2.5 on 2025-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0044_orcamentodepartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='aquisicao',
            name='patrimonio',
        ),
        migrations.DeleteModel(
            name='Patrimonio',
        ),
    ]
