# Generated by Django 4.2.5 on 2025-12-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0048_alter_aquisicao_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aquisicao',
            new_name='InventarioPatrimonio',
        ),
    ]
