# Generated by Django 4.2.5 on 2025-12-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0051_remove_inventariopatrimonio_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='localizacao',
            field=models.CharField(default='w', max_length=100),
            preserve_default=False,
        ),
    ]
