# Generated by Django 4.2.5 on 2025-12-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0052_inventariopatrimonio_localizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariopatrimonio',
            old_name='quemadquiriu',
            new_name='responsavel',
        ),
    ]
