# Generated by Django 4.2.5 on 2025-12-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0054_alter_inventariopatrimonio_moeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariopatrimonio',
            name='saiudacaixa',
        ),
        migrations.RemoveField(
            model_name='inventariopatrimonio',
            name='saiudobanco',
        ),
    ]
