# Generated by Django 4.2.5 on 2025-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0058_inventariopatrimonio_data_proxima_manutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='data_proxima_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Proxima Manutenção'),
        ),
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='data_ultima_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da ultima Manutenção'),
        ),
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='descricao_manutencao_realizada',
            field=models.TextField(blank=True, verbose_name='Descrição da manutenção realizada'),
        ),
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='registo_danos',
            field=models.TextField(blank=True, null=True, verbose_name='Registro de danos'),
        ),
    ]
