# Generated by Django 4.2.5 on 2025-12-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0060_inventariopatrimonio_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosaida',
            name='documento_justificativo',
            field=models.FileField(upload_to=''),
        ),
    ]
