# Generated by Django 4.2.5 on 2025-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0061_alter_pedidosaida_documento_justificativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosaida',
            name='documento_justificativo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
