# Generated by Django 4.2.5 on 2025-12-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0062_alter_pedidosaida_documento_justificativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ficheiro', models.FileField(blank=True, upload_to='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
            ],
        ),
    ]
