# Generated by Django 4.2.5 on 2025-12-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0063_conteudoensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaida',
            name='aprovador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprovador', to='sitetibl.irmao'),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='requerente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requerente', to='sitetibl.irmao'),
        ),
        migrations.CreateModel(
            name='EnvioMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('sms', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('quemenviou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
            ],
        ),
    ]
