# Generated by Django 4.2.5 on 2025-12-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0064_pedidosaida_aprovador_alter_pedidosaida_requerente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefones',
            new_name='telefone',
        ),
    ]
