# Generated by Django 4.2.5 on 2025-12-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0065_rename_telefones_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='vice_lider_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vice_lider_departamento', to='sitetibl.irmao'),
        ),
    ]
