# Generated by Django 4.2.5 on 2026-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0069_irmao_data_atualizacao_irmao_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmao',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
