# Generated by Django 4.2.5 on 2026-01-14 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0072_tipooferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimooferta',
            name='tipooferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipooferta', verbose_name='Tipo de oferta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dizimooferta',
            name='irmao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao', verbose_name='Irmao Dizimista'),
        ),
    ]
