# Generated by Django 4.1.4 on 2022-12-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=100, unique=True, verbose_name='Designação')),
                ('abreviacao', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Abreviação')),
                ('gestor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gestor')),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Cestabasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DateField(unique=True)),
                ('valordisponibilizado', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Custo[AKZ]')),
                ('Datadisponvalor', models.DateField(blank=True, null=True, verbose_name='Valor diponiblizado aos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=100, unique=True, verbose_name='Designação')),
                ('abreviacao', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Abreviação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Listaactividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50)),
                ('unidades', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=30, verbose_name='Apelido')),
                ('outrosnomes', models.CharField(blank=True, max_length=60, verbose_name='Outros Nomes')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/static/fotos/%Y')),
                ('datanascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('estadocivil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viuvo(a)'), ('A', 'Amaritado(a)')], default='S', max_length=30, verbose_name='Estado Civil')),
                ('grauescolaridade', models.CharField(blank=True, choices=[('basico', 'Básico'), ('medio', 'Médio'), ('superior', 'Superior')], max_length=50, verbose_name='Grau de Escolaridade')),
                ('localdetrabalho', models.CharField(blank=True, max_length=50, verbose_name='Local de Trabalho')),
                ('ruaenumero', models.CharField(blank=True, max_length=60, verbose_name='Rua e Número')),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, choices=[('BE', 'Belas'), ('LU', 'Luanda'), ('CA', 'Cacuaco'), ('IC', 'Icolo e Bengo'), ('VI', 'Viana'), ('KI', 'Kilamba Kiaxi'), ('QU', 'Quissama')], max_length=50, verbose_name='Município')),
                ('provincia', models.CharField(choices=[('BNG', 'Bengo'), ('BGL', 'Benguela'), ('BIE', 'Bié'), ('CAB', 'Cabinda'), ('CNE', 'Cunene'), ('HMB', 'Huambo'), ('HLA', 'Huila'), ('KKG', 'Kuando kubango'), ('KZN', 'Kuanza Norte'), ('KZS', 'Kuanza Sul'), ('LDA', 'Luanda'), ('LDN', 'Lunda Norte'), ('LDS', 'Lunda Sul'), ('MLG', 'Malange'), ('MXC', 'Moxico'), ('NMB', 'Namibe'), ('UGE', 'Uige'), ('ZAR', 'Zaire')], default='LDA', max_length=50, verbose_name='Província')),
                ('telefones', models.CharField(blank=True, max_length=50, verbose_name='Telefones')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=100, unique=True, verbose_name='Designação')),
                ('ruaenumero', models.CharField(blank=True, max_length=60, verbose_name='Rua e Número')),
                ('bairro', models.CharField(blank=True, max_length=30)),
                ('municipio', models.CharField(blank=True, max_length=60)),
                ('provincia', models.CharField(choices=[('BNG', 'Bengo'), ('BGL', 'Benguela'), ('BIE', 'Bié'), ('CAB', 'Cabinda'), ('CNE', 'Cunene'), ('HMB', 'Huambo'), ('HLA', 'Huila'), ('KKG', 'Kuando kubango'), ('KZN', 'Kuanza Norte'), ('KZS', 'Kuanza Sul'), ('LDA', 'Luanda'), ('LDN', 'Lunda Norte'), ('LDS', 'Lunda Sul'), ('MLG', 'Malange'), ('MXC', 'Moxico'), ('NMB', 'Namibe'), ('UGE', 'Uige'), ('ZAR', 'Zaire')], default='LDA', max_length=30)),
                ('dataFundacao', models.DateField(blank=True, default=None, null=True, verbose_name='Data de Fundação')),
                ('numerodemembros', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('1', 'Igreja'), ('2', 'Célula'), ('3', 'Posto de Pregação'), ('4', 'Colégio')], max_length=3)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Irmao',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sitetibl.pessoa')),
                ('culto', models.CharField(choices=[('P', 'Português'), ('I', 'Inglês')], default='P', max_length=2)),
                ('dizimista', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=10)),
                ('celula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.sitio')),
            ],
            bases=('sitetibl.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.profissao'),
        ),
        migrations.CreateModel(
            name='Contabancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroconta', models.CharField(max_length=100, unique=True, verbose_name='Número da conta')),
                ('iban', models.CharField(max_length=100, unique=True, verbose_name='IBAN')),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitetibl.banco')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.sitio')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precounitario', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitetibl.cestabasica')),
            ],
        ),
        migrations.CreateModel(
            name='Ajuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Saude'), ('2', 'Falecimento'), ('3', 'Propina'), ('4', 'Cesta básica'), ('5', 'Casamento'), ('6', 'Outra')], default='6', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Valor[AKZ]')),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.pessoa')),
                ('cesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.cestabasica')),
                ('patrocinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valordoador', to='sitetibl.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Actividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(max_length=10)),
                ('fim', models.TimeField(max_length=60)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=60)),
                ('tema', models.CharField(blank=True, max_length=500)),
                ('versosbiblicos', models.CharField(blank=True, max_length=200)),
                ('hinos', models.CharField(blank=True, max_length=300)),
                ('totalpresentes', models.IntegerField(default=2)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('designacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitetibl.listaactividades')),
            ],
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Desde')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Até')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.departamento')),
                ('irmao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao', verbose_name='Irmão')),
            ],
            options={
                'unique_together': {('irmao', 'departamento', 'cargo', 'inicio')},
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.actividade')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.funcao')),
                ('irmao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
            ],
            options={
                'unique_together': {('irmao', 'actividade', 'funcao')},
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='integrantes',
            field=models.ManyToManyField(blank=True, through='sitetibl.Mandato', to='sitetibl.irmao'),
        ),
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('quantidade', models.IntegerField()),
                ('custo', models.BigIntegerField()),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], max_length=10)),
                ('data', models.DateField(null=True, verbose_name='Data de aquisição')),
                ('estado', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Velho', 'Velho')], max_length=5)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('patrimonio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.patrimonio')),
                ('quemadquiriu', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.irmao')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.TextField()),
                ('quemanuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitetibl.irmao')),
            ],
        ),
        migrations.AddField(
            model_name='actividade',
            name='participantes',
            field=models.ManyToManyField(related_name='particact', through='sitetibl.Escala', to='sitetibl.irmao'),
        ),
    ]
