# Generated by Django 4.1.4 on 2022-12-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0002_alter_sitio_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irmao',
            name='celula',
        ),
        migrations.AddField(
            model_name='irmao',
            name='congregacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.sitio', verbose_name='Congregação'),
        ),
    ]
