# Generated by Django 4.1.4 on 2022-12-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0003_remove_irmao_celula_irmao_congregacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividade',
            name='local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.sitio'),
        ),
    ]
