# Generated by Django 4.1.4 on 2023-01-20 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0005_alter_pessoa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruporubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubricaentrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
                ('gruporubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.gruporubrica')),
            ],
        ),
        migrations.CreateModel(
            name='Rubricasaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
                ('gruporubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.gruporubrica')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoajuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='localizacao',
            old_name='nome',
            new_name='designacao',
        ),
        migrations.RemoveField(
            model_name='ajuda',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='cestabasica',
            name='valordisponibilizado',
        ),
        migrations.RemoveField(
            model_name='irmao',
            name='congregacao',
        ),
        migrations.AddField(
            model_name='aquisicao',
            name='fabricante',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aquisicao',
            name='modelo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irmao',
            name='celula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.sitio'),
        ),
        migrations.AlterField(
            model_name='actividade',
            name='designacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.listaactividades'),
        ),
        migrations.AlterField(
            model_name='actividade',
            name='local',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='quemanuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao'),
        ),
        migrations.AlterField(
            model_name='aquisicao',
            name='patrimonio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.patrimonio'),
        ),
        migrations.AlterField(
            model_name='aquisicao',
            name='quemadquiriu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitetibl.irmao'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='designacao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='composicaocesta',
            name='cesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.cestabasica'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.banco'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.sitio'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.pessoa'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.funcao'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estadocivil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('V', 'Viuvo'), ('A', 'Amaritado')], default='S', max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='municipio',
            field=models.CharField(blank=True, choices=[('BE', 'Belas'), ('LU', 'Luanda'), ('CA', 'Cacuaco'), ('IC', 'Icolo e Bengo'), ('VI', 'Viana'), ('QU', 'Quissama')], max_length=50, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='municipio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='Saidacaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('datacontrolo', models.DateField(auto_now=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricasaida')),
            ],
        ),
        migrations.CreateModel(
            name='Saidabanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('datacontrolo', models.DateField(auto_now=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.contabancaria')),
                ('contaaacreditar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contadestino', to='sitetibl.contabancaria')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricaentrada')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentoservico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('saiudacaixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa')),
                ('saiudobanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Entradacaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricaentrada')),
            ],
        ),
        migrations.CreateModel(
            name='Entradabanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('via', models.CharField(choices=[('1', 'Depósito'), ('2', 'Transferência bancária'), ('3', 'Multicaixa')], max_length=200)),
                ('datacontrolo', models.DateField(auto_now=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('contaaacreditar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.contabancaria')),
                ('contaorigem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contadeprovinencia', to='sitetibl.contabancaria')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricaentrada')),
            ],
        ),
        migrations.CreateModel(
            name='Dizimooferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('datacorrespondente', models.DateField()),
                ('datacontrolo', models.DateField(auto_now=True)),
                ('dataregisto', models.DateField(default=datetime.datetime.today)),
                ('actividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.actividade')),
                ('entradabanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.entradabanco')),
                ('entradacaixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.entradacaixa')),
                ('irmao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao', verbose_name='irmaodizimista')),
            ],
        ),
        migrations.AddField(
            model_name='ajuda',
            name='ajuda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipoajuda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuda',
            name='saiudacaixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa'),
        ),
        migrations.AddField(
            model_name='ajuda',
            name='saiudobanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco'),
        ),
        migrations.AddField(
            model_name='aquisicao',
            name='saiudacaixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa'),
        ),
        migrations.AddField(
            model_name='aquisicao',
            name='saiudobanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco'),
        ),
        migrations.AddField(
            model_name='cestabasica',
            name='saiudacaixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa'),
        ),
        migrations.AddField(
            model_name='cestabasica',
            name='saiudobanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco'),
        ),
    ]
