# Generated by Django 4.1.4 on 2023-10-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0007_remove_actividade_local_alter_aquisicao_quemadquiriu'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='localactividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sitetibl.sitio'),
        ),
    ]
