# Generated by Django 4.2.5 on 2025-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0008_actividade_localactividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='especialidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estadocivil',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viuvo(a)'), ('A', 'Amaritado(a)'), ('D', 'Divorciado(a)')], default='S', max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='municipio',
            field=models.CharField(blank=True, choices=[('BE', 'Belas'), ('CZ', 'Cazenga'), ('KK', 'Kilamba Kiaxi'), ('LU', 'Luanda'), ('CA', 'Cacuaco'), ('IC', 'Icolo e Bengo'), ('TT', 'Talatona'), ('VI', 'Viana'), ('QU', 'Quissama')], max_length=50, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='tipo',
            field=models.CharField(choices=[('1', 'Igreja'), ('2', 'Célula'), ('3', 'Posto de Pregação'), ('4', 'Colégio'), ('5', 'Missão')], max_length=3),
        ),
    ]
