# Generated by Django 4.2.5 on 2025-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0009_pessoa_especialidade_alter_pessoa_estadocivil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmao',
            name='batizado',
            field=models.BooleanField(default=False),
        ),
    ]
