# Generated by Django 4.2.5 on 2025-11-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0012_irmao_igreja_alter_irmao_celula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irmao',
            old_name='igreja',
            new_name='localcongregacao',
        ),
    ]
