# Generated by Django 4.2.5 on 2025-12-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0015_rename_moemntos_realizados_relatoriosemanalcelula_moementos_realizados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriosemanalcelula',
            old_name='moementos_realizados',
            new_name='momentos_realizados',
        ),
    ]
