# Generated by Django 4.2.5 on 2025-12-02 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0016_rename_moementos_realizados_relatoriosemanalcelula_momentos_realizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriosemanalcelula',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relatoriosemanalcelula',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
