# Generated by Django 4.2.5 on 2025-12-05 20:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0017_relatoriosemanalcelula_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosemanalcelula',
            name='momentos_realizados',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('louvor', 'Louvor'), ('oração', 'Oração'), ('momento da palavra', 'Momento Da Palavra'), ('partilha de testemunhos', 'Partilha De Testemunhos'), ('intercessão', 'Intercessão'), ('tempo de comunhão', 'Tempo de Comunhão')], max_length=50),
        ),
    ]
