# Generated by Django 4.2.5 on 2025-12-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0020_alter_pedidosaida_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosaida',
            name='status_de_aprovacao',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('análise', 'Em Análise')], max_length=50),
        ),
    ]
