# Generated by Django 4.2.5 on 2025-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0021_alter_pedidosaida_status_de_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosaida',
            name='status_de_aprovacao',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Em Análise', 'Em Análise')], max_length=50),
        ),
    ]
