# Generated by Django 4.2.5 on 2025-12-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0023_alter_relatoriosemanalcelula_lider_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200)),
            ],
        ),
    ]
