# Generated by Django 4.2.5 on 2025-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0024_momentosrealizados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriosemanalcelula',
            name='momentos_realizados',
        ),
        migrations.AddField(
            model_name='relatoriosemanalcelula',
            name='momentos_realizados',
            field=models.ManyToManyField(to='sitetibl.momentosrealizados'),
        ),
    ]
