# Generated by Django 4.2.5 on 2025-12-09 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0026_departamento_lider_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosaida',
            name='area',
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.departamento'),
        ),
    ]
