# Generated by Django 4.2.5 on 2025-12-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0029_alter_relatoriosemanalcelula_nome_celula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosemanalcelula',
            name='nome_celula',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
    ]
