# Generated by Django 4.2.5 on 2025-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0030_alter_relatoriosemanalcelula_nome_celula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosemanalcelula',
            name='nome_celula',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
