# Generated by Django 4.2.5 on 2025-12-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0034_relatoriosemanalcelula_nome_celula1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriosemanalcelula',
            name='nome_celula',
        ),
    ]
