# Generated by Django 4.2.5 on 2025-12-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0038_pedidosaida_centro_custo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosaida',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='pedidosaida',
            name='status_de_aprovacao',
        ),
        migrations.RemoveField(
            model_name='pedidosaida',
            name='tipificacao_custo',
        ),
    ]
