# Generated by Django 4.2.5 on 2025-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0040_rename_centro_custo1_pedidosaida_centro_custo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=20)),
            ],
        ),
    ]
