# Generated by Django 4.2.5 on 2025-12-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0041_tipo_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaida',
            name='moeda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipo_moeda'),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='montante',
            field=models.FloatField(),
        ),
    ]
