# Generated by Django 4.2.5 on 2025-12-09 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0042_pedidosaida_moeda_alter_pedidosaida_montante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaida',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
