# Generated by Django 4.2.5 on 2025-12-11 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0045_categoria_patrimonio_remove_aquisicao_patrimonio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisicao',
            name='categoria_patrimonio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.categoria_patrimonio'),
        ),
    ]
