# Generated by Django 4.2.5 on 2025-12-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0047_estado_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquisicao',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.estado_patrimonio'),
        ),
    ]
