# Generated by Django 4.2.5 on 2025-12-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0049_rename_aquisicao_inventariopatrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='descricao',
            field=models.CharField(default='w', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='nome',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
