# Generated by Django 4.2.5 on 2025-12-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0050_inventariopatrimonio_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariopatrimonio',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='inventariopatrimonio',
            name='modelo',
        ),
    ]
