# Generated by Django 4.2.5 on 2025-12-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0053_rename_quemadquiriu_inventariopatrimonio_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='moeda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipo_moeda'),
        ),
    ]
