# Generated by Django 4.2.5 on 2025-12-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0055_remove_inventariopatrimonio_saiudacaixa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariopatrimonio',
            old_name='data',
            new_name='data_aquisicao',
        ),
        migrations.RenameField(
            model_name='inventariopatrimonio',
            old_name='custo',
            new_name='preco',
        ),
    ]
