# Generated by Django 4.2.5 on 2025-12-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0056_rename_data_inventariopatrimonio_data_aquisicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='foto',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
