# Generated by Django 4.2.5 on 2025-12-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0057_inventariopatrimonio_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='data_proxima_manutencao',
            field=models.DateField(null=True, verbose_name='Data da Proxima Manutenção'),
        ),
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='data_ultima_manutencao',
            field=models.DateField(null=True, verbose_name='Data da ultima Manutenção'),
        ),
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='descricao_manutencao_realizada',
            field=models.TextField(default='w'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='registo_danos',
            field=models.TextField(default='w'),
            preserve_default=False,
        ),
    ]
