# Generated by Django 4.2.5 on 2025-12-11 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0059_alter_inventariopatrimonio_data_proxima_manutencao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventariopatrimonio',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventariopatrimonio',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisição'),
        ),
    ]
