# Generated by Django 4.2.20 on 2025-12-31 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sitetibl", "0067_irmao_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irmao",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Django",
            ),
        ),
    ]
