# Generated by Django 4.2.5 on 2026-01-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0071_alter_irmao_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
