# Generated by Django 5.2.11 on 2026-02-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0073_dizimooferta_tipooferta_alter_dizimooferta_irmao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
