# Generated by Django 4.2.5 on 2026-02-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0073_dizimooferta_tipooferta_alter_dizimooferta_irmao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='saldo',
        ),
    ]
