# Generated by Django 4.2.5 on 2026-02-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0074_remove_contabancaria_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
