# Generated by Django 4.2.5 on 2026-02-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0075_contabancaria_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradabanco',
            name='contaaacreditar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.contabancaria'),
        ),
    ]
