# Generated by Django 6.0.3 on 2026-03-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0077_merge_20260313_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='profissao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Profissão'),
        ),
    ]
