# Generated by Django 6.0.3 on 2026-03-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0082_actividade_criado_por_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcoes', to='sitetibl.departamento'),
        ),
    ]
