# Generated by Django 6.0.3 on 2026-03-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0083_funcao_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaida',
            name='comprovativo_pagamento',
            field=models.FileField(blank=True, upload_to='comprovativos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='estado_pagamento',
            field=models.CharField(choices=[('nao_aplicavel', 'Não Aplicável'), ('aguardando', 'Aguardando Pagamento'), ('pago', 'Pago')], default='nao_aplicavel', max_length=20, verbose_name='Estado de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='observacao_aprovador',
            field=models.TextField(blank=True, verbose_name='Observação do Aprovador'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='funcao',
            field=models.CharField(choices=[('membro', 'Membro'), ('lider', 'Líder'), ('vice_lider', 'Vice-Líder'), ('secretario', 'Secretário(a)'), ('tesoureiro', 'Tesoureiro(a)'), ('coordenador', 'Coordenador(a)')], default='membro', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='documento_justificativo',
            field=models.FileField(blank=True, upload_to='pedidos/'),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='projecto',
            field=models.CharField(max_length=100, verbose_name='Projecto / Finalidade'),
        ),
    ]
