# Generated by Django 6.0.3 on 2026-03-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0084_pedidosaida_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Números separados por vírgula (0=Segunda … 6=Domingo)', max_length=20, verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='actividade',
            name='is_recorrente',
            field=models.BooleanField(default=False, verbose_name='É recorrente'),
        ),
        migrations.AddField(
            model_name='actividade',
            name='recorrencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Recorrência até'),
        ),
    ]
