# Generated by Django 6.0.3 on 2026-03-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_rename_indexes'),
        ('sitetibl', '0085_recorrencia_actividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividade', to='schedule.event', verbose_name='Evento (scheduler)'),
        ),
        migrations.AddField(
            model_name='actividade',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='sitetibl.actividade', verbose_name='Série pai'),
        ),
    ]
