# Generated by Django 5.2.11 on 2026-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0086_scheduler_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda',
            name='ajuda',
            field=models.CharField(max_length=200, verbose_name='Ajuda'),
        ),
    ]
