# Generated by Django 6.0.3 on 2026-04-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0088_enviomensagem_destinatarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda',
            name='saiudacaixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa', verbose_name='Saiu da caixa'),
        ),
        migrations.AlterField(
            model_name='ajuda',
            name='saiudobanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco', verbose_name='Saiu do banco'),
        ),
        migrations.AlterField(
            model_name='cestabasica',
            name='saiudacaixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa', verbose_name='Saiu da caixa'),
        ),
        migrations.AlterField(
            model_name='cestabasica',
            name='saiudobanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco', verbose_name='Saiu do banco'),
        ),
        migrations.AlterField(
            model_name='pagamentoservico',
            name='saiudacaixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidacaixa', verbose_name='Saiu da caixa'),
        ),
        migrations.AlterField(
            model_name='pagamentoservico',
            name='saiudobanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saidabanco', verbose_name='Saiu do banco'),
        ),
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=200, unique=True, verbose_name='Designação')),
                ('local_reuniao', models.CharField(blank=True, max_length=200, verbose_name='Local de Reunião')),
                ('dia_reuniao', models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia de Reunião')),
                ('hora_reuniao', models.TimeField(blank=True, null=True, verbose_name='Hora de Reunião')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celula_lider', to='sitetibl.irmao', verbose_name='Líder')),
                ('vice_lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celula_vice_lider', to='sitetibl.irmao', verbose_name='Vice-Líder')),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'ordering': ['designacao'],
            },
        ),
        migrations.AddField(
            model_name='relatoriosemanalcelula',
            name='celula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='sitetibl.celula', verbose_name='Célula'),
        ),
        migrations.CreateModel(
            name='NotificacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoInterdepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('material_criativo', 'Material Criativo'), ('equipamento', 'Equipamento'), ('verba', 'Verba'), ('cobertura_evento', 'Cobertura de Evento'), ('apoio_logistico', 'Apoio Logístico'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Categoria')),
                ('data_necessidade', models.DateField(verbose_name='Data de Necessidade')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('documento_anexo', models.FileField(blank=True, upload_to='solicitacoes/', verbose_name='Documento Anexo')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Estado')),
                ('justificacao_resposta', models.TextField(blank=True, verbose_name='Justificação da Resposta')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('departamento_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to='sitetibl.departamento', verbose_name='Departamento Destinatário')),
                ('departamento_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='sitetibl.departamento', verbose_name='Departamento Solicitante')),
                ('responsavel_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_respondidas', to='sitetibl.irmao', verbose_name='Responsável pela Resposta')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_criadas', to='sitetibl.irmao', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação Interdepartamental',
                'verbose_name_plural': 'Solicitações Interdepartamentais',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado Anterior')),
                ('estado_novo', models.CharField(max_length=20, verbose_name='Estado Novo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao', verbose_name='Responsável')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='sitetibl.solicitacaointerdepartamental')),
            ],
            options={
                'verbose_name': 'Histórico de Solicitação',
                'verbose_name_plural': 'Históricos de Solicitação',
                'ordering': ['data'],
            },
        ),
    ]
