# Generated by Django 6.0.3 on 2026-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0089_alter_ajuda_saiudacaixa_alter_ajuda_saiudobanco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('concluido', 'Concluído')], max_length=20, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='estado_novo',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('concluido', 'Concluído')], max_length=20, verbose_name='Estado Novo'),
        ),
    ]
