# Generated by Django 6.0.3 on 2026-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0090_alter_historicosolicitacao_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosolicitacao',
            name='documento_anexo',
            field=models.FileField(blank=True, upload_to='solicitacoes/historico/', verbose_name='Documento Anexo'),
        ),
    ]
