# Generated by Django 6.0.3 on 2026-04-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0091_historicosolicitacao_documento_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('anexo', models.FileField(blank=True, upload_to='solicitacoes/comentarios/', verbose_name='Anexo')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao', verbose_name='Autor')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='sitetibl.solicitacaointerdepartamental')),
            ],
            options={
                'verbose_name': 'Comentário de Solicitação',
                'verbose_name_plural': 'Comentários de Solicitação',
                'ordering': ['data'],
            },
        ),
    ]
