# Generated by Django 6.0.3 on 2026-04-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0092_comentariosolicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('luto', 'Luto'), ('doenca', 'Doença'), ('aconselhamento', 'Aconselhamento'), ('crise_familiar', 'Crise Familiar'), ('hospitalizacao', 'Hospitalização'), ('necessidade_material', 'Necessidade Material'), ('integracao', 'Integração de Novo Membro'), ('restauracao', 'Restauração'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('estado', models.CharField(choices=[('aberto', 'Aberto'), ('em_acompanhamento', 'Em Acompanhamento'), ('resolvido', 'Resolvido'), ('encerrado', 'Encerrado')], default='aberto', max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('confidencial', models.BooleanField(default=True, verbose_name='Confidencial')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Actualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_criados', to='sitetibl.irmao', verbose_name='Criado por')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_pastorais', to='sitetibl.irmao', verbose_name='Membro')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_atribuidos', to='sitetibl.irmao', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Caso Pastoral',
                'verbose_name_plural': 'Casos Pastorais',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='AlertaPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inactividade', 'Inactividade Prolongada'), ('novo_sem_acompanhamento', 'Novo Convertido sem Acompanhamento'), ('sem_celula', 'Sem Célula Atribuída'), ('ausencia_dizimo', 'Ausência de Dízimo'), ('aniversario', 'Aniversário'), ('visitante_recorrente', 'Visitante Recorrente'), ('queda_celula', 'Queda de Participação na Célula'), ('manual', 'Alerta Manual')], max_length=30, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('visto', 'Visto'), ('em_tratamento', 'Em Tratamento'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='novo', max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_json', models.JSONField(blank=True, default=dict, verbose_name='Dados de Contexto')),
                ('gerado_automaticamente', models.BooleanField(default=True, verbose_name='Gerado Automaticamente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Actualização')),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_pastorais', to='sitetibl.sitio', verbose_name='Célula')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_pastorais', to='sitetibl.irmao', verbose_name='Membro')),
                ('caso_associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='sitetibl.casopastoral', verbose_name='Caso Associado')),
            ],
            options={
                'verbose_name': 'Alerta Pastoral',
                'verbose_name_plural': 'Alertas Pastorais',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistoAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(choices=[('visita_domiciliar', 'Visita Domiciliar'), ('chamada_telefonica', 'Chamada Telefónica'), ('mensagem', 'Mensagem (WhatsApp/SMS)'), ('reuniao_presencial', 'Reunião Presencial'), ('oracao', 'Oração'), ('encaminhamento', 'Encaminhamento'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Contacto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('documento_anexo', models.FileField(blank=True, upload_to='pastoral/registos/', verbose_name='Documento Anexo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('proximo_passo', models.TextField(blank=True, verbose_name='Próximo Passo')),
                ('data_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Data do Próximo Contacto')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos', to='sitetibl.casopastoral', verbose_name='Caso')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetibl.irmao', verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registo de Acompanhamento',
                'verbose_name_plural': 'Registos de Acompanhamento',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='VisitanteRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('visitante', 'Visitante'), ('em_integracao', 'Em Integração'), ('integrado', 'Integrado (tornou-se membro)'), ('desistiu', 'Desistiu')], default='visitante', max_length=20, verbose_name='Estado')),
                ('numero_visitas', models.IntegerField(default=1, verbose_name='Número de Visitas')),
                ('primeira_visita', models.DateField(verbose_name='Primeira Visita')),
                ('ultima_visita', models.DateField(verbose_name='Última Visita')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Actualização')),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes_recorrentes', to='sitetibl.sitio', verbose_name='Célula')),
                ('irmao_convertido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitante_origem', to='sitetibl.irmao', verbose_name='Membro Convertido')),
                ('responsavel_integracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_acompanhados', to='sitetibl.irmao', verbose_name='Responsável pela Integração')),
            ],
            options={
                'verbose_name': 'Visitante Recorrente',
                'verbose_name_plural': 'Visitantes Recorrentes',
                'ordering': ['-ultima_visita'],
            },
        ),
    ]
