# Generated by Django 6.0.3 on 2026-04-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0093_pastoral_care_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitanterecorrente',
            name='celula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitantes_recorrentes', to='sitetibl.sitio', verbose_name='Célula'),
        ),
    ]
