# Generated by Django 6.0.3 on 2026-04-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0094_alter_visitanterecorrente_celula'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.centro_custo', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='comprovativo_pagamento',
            field=models.FileField(blank=True, upload_to='comprovativos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='estado_pagamento',
            field=models.CharField(choices=[('nao_aplicavel', 'Não Aplicável'), ('aguardando', 'Aguardando Pagamento'), ('pago', 'Pago')], default='nao_aplicavel', max_length=20, verbose_name='Estado de Pagamento'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='justificativa_custo',
            field=models.TextField(blank=True, verbose_name='Justificativa de Custo'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='moeda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipo_moeda', verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='montante',
            field=models.FloatField(blank=True, null=True, verbose_name='Montante'),
        ),
        migrations.AddField(
            model_name='solicitacaointerdepartamental',
            name='tipificacao_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.tipificacao_custo', verbose_name='Tipificação de Custo'),
        ),
    ]
