# Generated by Django 5.2.11 on 2026-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0095_solicitacaointerdepartamental_centro_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='funcao',
            field=models.CharField(choices=[('membro', 'Membro'), ('lider', 'Líder'), ('vice_lider', 'Vice-Líder'), ('secretario', 'Secretário departamental'), ('secretario_geral', 'Secretário Geral'), ('tesoureiro', 'Tesoureiro(a)'), ('coordenador', 'Coordenador(a)')], default='membro', max_length=20, verbose_name='Cargo'),
        ),
    ]
