# Generated by Django 5.2.11 on 2026-06-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0096_add_secretario_geral_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='eh_protocolo',
            field=models.BooleanField(default=False, help_text='Marque se esta escala é para protocolo (permite múltiplos irmãos)', verbose_name='É Protocolo?'),
        ),
        migrations.AddField(
            model_name='escala',
            name='irmao_protocolo',
            field=models.ManyToManyField(blank=True, help_text='Selecione até 10 irmãos para protocolo', related_name='escalas_protocolo', to='sitetibl.irmao', verbose_name='Irmãos do Protocolo (máx. 10)'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='irmao',
            field=models.ForeignKey(help_text='Irmão principal da escala', on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='funcao',
            field=models.CharField(choices=[('membro', 'Membro'), ('lider', 'Líder'), ('vice_lider', 'Vice-Líder'), ('secretario', 'Secretário(a) departamental'), ('secretario_geral', 'Secretário(a) Geral'), ('tesoureiro', 'Tesoureiro(a)'), ('coordenador', 'Coordenador(a)')], default='membro', max_length=20, verbose_name='Cargo'),
        ),
    ]
