# Generated by Django 5.2.11 on 2026-05-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0096_add_secretario_geral_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='funcao',
            field=models.CharField(choices=[('membro', 'Membro'), ('lider', 'Líder'), ('vice_lider', 'Vice-Líder'), ('secretario', 'Secretário(a) departamental'), ('secretario_geral', 'Secretário(a) Geral'), ('tesoureiro', 'Tesoureiro(a)'), ('coordenador', 'Coordenador(a)')], default='membro', max_length=20, verbose_name='Cargo'),
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Protocolo')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('interno', 'Interno')], max_length=20, verbose_name='Tipo')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('remetente', models.CharField(blank=True, max_length=200, verbose_name='Remetente')),
                ('destinatario', models.CharField(blank=True, max_length=200, verbose_name='Destinatário')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_processamento', 'Em Processamento'), ('processado', 'Processado'), ('arquivado', 'Arquivado')], default='novo', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('documento', models.FileField(blank=True, upload_to='protocolos/', verbose_name='Documento')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_responsavel', to='sitetibl.irmao', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
