# Generated by Django 5.2.11 on 2026-05-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0097_alter_mandato_funcao_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='actividade_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_actividade', to='sitetibl.actividade', verbose_name='Actividade Principal'),
        ),
    ]
