# Generated by Django 5.2.11 on 2026-05-27 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0098_protocolo_actividade_principal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número da Ata')),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizada', 'Finalizada'), ('revisada', 'Revisada'), ('assinada', 'Assinada')], default='rascunho', max_length=20, verbose_name='Estado')),
                ('data_realizacao', models.DateField(blank=True, null=True, verbose_name='Data de Realização')),
                ('hora_inicio_real', models.TimeField(blank=True, null=True, verbose_name='Hora de Início (Real)')),
                ('hora_fim_real', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim (Real)')),
                ('local_realizado', models.CharField(blank=True, max_length=200, verbose_name='Local Realizado')),
                ('total_escalados', models.IntegerField(default=0, verbose_name='Total de Escalados')),
                ('total_presentes', models.IntegerField(default=0, verbose_name='Total de Presentes')),
                ('total_ausentes', models.IntegerField(default=0, verbose_name='Total de Ausentes')),
                ('resumo_atividade', models.TextField(blank=True, verbose_name='Resumo da Atividade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('pontos_positivos', models.TextField(blank=True, verbose_name='Pontos Positivos')),
                ('pontos_melhorar', models.TextField(blank=True, verbose_name='Pontos a Melhorar')),
                ('acoes_proximas', models.TextField(blank=True, verbose_name='Ações Próximas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('actividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ata_protocolo', to='sitetibl.actividade', verbose_name='Atividade')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_responsavel', to='sitetibl.irmao', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ata de Protocolo',
                'verbose_name_plural': 'Atas de Protocolo',
                'ordering': ['-data_realizacao'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteAtaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Ausente Justificado')], default='presente', max_length=20, verbose_name='Presença')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='sitetibl.ataprotocolo', verbose_name='Ata')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_ata', to='sitetibl.funcao', verbose_name='Função')),
                ('irmao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_ata', to='sitetibl.irmao', verbose_name='Irmão')),
            ],
            options={
                'verbose_name': 'Participante de Ata',
                'verbose_name_plural': 'Participantes de Ata',
                'ordering': ['irmao__nome'],
                'unique_together': {('ata', 'irmao')},
            },
        ),
    ]
