# Generated by Django 4.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0099_irmao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmao',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('membro_batizado', 'Membro'),
                    ('crianca', 'Criança'),
                    ('assistente', 'Assistente'),
                ],
                default='assistente',
                max_length=20,
                verbose_name='Categoria',
            ),
        ),
    ]
