# Generated by Django 4.2.5 on 2026-07-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0097_escala_eh_protocolo_escala_irmao_protocolo_and_more'),
        ('sitetibl', '0100_alter_irmao_categoria'),
    ]

    operations = [
    ]
