# Generated by Django 4.2.5 on 2026-07-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0101_merge_20260702_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviomensagem',
            name='email',
            field=models.BooleanField(default=False, verbose_name='Enviar por Email'),
        ),
        migrations.AlterField(
            model_name='enviomensagem',
            name='sms',
            field=models.BooleanField(default=False, verbose_name='Enviar por SMS'),
        ),
        migrations.AlterField(
            model_name='saidabanco',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricasaida'),
        ),
    ]
