# Generated by Django 4.2.5 on 2026-07-02 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0102_fix_saidabanco_rubrica_to_rubricasaida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('caixa', 'Caixa'), ('banco', 'Banco')], default='caixa', max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('datacontrolo', models.DateField(auto_now=True)),
                ('via', models.CharField(blank=True, choices=[('1', 'Depósito'), ('2', 'Transferência bancária'), ('3', 'Multicaixa')], max_length=200, verbose_name='Via')),
                ('contaaacreditar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.contabancaria', verbose_name='Conta a creditar')),
                ('contaorigem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_origem', to='sitetibl.contabancaria', verbose_name='Conta origem (transferência)')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricaentrada')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('caixa', 'Caixa'), ('banco', 'Banco')], default='caixa', max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('datacontrolo', models.DateField(auto_now=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.contabancaria', verbose_name='Conta')),
                ('contaaacreditar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saidas_destino', to='sitetibl.contabancaria', verbose_name='Conta a creditar (transferência)')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.rubricasaida')),
            ],
        ),
        migrations.RemoveField(
            model_name='entradacaixa',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='entradacaixa',
            name='rubrica',
        ),
        migrations.RemoveField(
            model_name='saidabanco',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='saidabanco',
            name='contaaacreditar',
        ),
        migrations.RemoveField(
            model_name='saidabanco',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='saidabanco',
            name='rubrica',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='rubrica',
        ),
        migrations.RemoveField(
            model_name='ajuda',
            name='saiudacaixa',
        ),
        migrations.RemoveField(
            model_name='ajuda',
            name='saiudobanco',
        ),
        migrations.RemoveField(
            model_name='cestabasica',
            name='saiudacaixa',
        ),
        migrations.RemoveField(
            model_name='cestabasica',
            name='saiudobanco',
        ),
        migrations.RemoveField(
            model_name='dizimooferta',
            name='entradabanco',
        ),
        migrations.RemoveField(
            model_name='dizimooferta',
            name='entradacaixa',
        ),
        migrations.RemoveField(
            model_name='pagamentoservico',
            name='saiudacaixa',
        ),
        migrations.RemoveField(
            model_name='pagamentoservico',
            name='saiudobanco',
        ),
        migrations.DeleteModel(
            name='Entradabanco',
        ),
        migrations.DeleteModel(
            name='Entradacaixa',
        ),
        migrations.DeleteModel(
            name='Saidabanco',
        ),
        migrations.DeleteModel(
            name='Saidacaixa',
        ),
        migrations.AddField(
            model_name='ajuda',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saida', verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='cestabasica',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saida', verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='dizimooferta',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.entrada'),
        ),
        migrations.AddField(
            model_name='pagamentoservico',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitetibl.saida', verbose_name='Saída'),
        ),
    ]
