# Generated by Django 4.2.5 on 2026-09-04 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitetibl', '0103_entrada_saida_remove_entradacaixa_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dizimo', 'Dízimo'), ('oferta', 'Oferta'), ('oferta_missionaria', 'Oferta Missionária'), ('oferta_construcao', 'Oferta para Construção'), ('doacao', 'Doação'), ('outra', 'Outra')], default='dizimo', max_length=30, verbose_name='Tipo de Contribuição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('moeda', models.CharField(choices=[('AKZ', 'Kwanza'), ('USD', 'USA Dólar'), ('EU', 'Euro'), ('R', 'Reais'), ('RAN', 'ZA Rands'), ('NAMD', 'Dólar Namibiano'), ('LB', 'Libra Inglesa')], default='AKZ', max_length=50, verbose_name='Moeda')),
                ('data', models.DateField(default=datetime.datetime.today, verbose_name='Data da Contribuição')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='comprovativos/', verbose_name='Comprovativo')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Estado')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('nota_validacao', models.TextField(blank=True, null=True, verbose_name='Nota de Validação')),
                ('irmao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitetibl.irmao', verbose_name='Membro')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
                'ordering': ['-data', '-data_registo'],
            },
        ),
    ]
