# Generated by Django 4.2.5 on 2026-09-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitetibl', '0104_contribuicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistActividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_actualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Actualização')),
                ('actividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='sitetibl.actividade', verbose_name='Actividade')),
            ],
            options={
                'verbose_name': 'Checklist de Actividade',
                'verbose_name_plural': 'Checklists de Actividades',
            },
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('rejeitada', 'Rejeitada/Anulada')], default='pendente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sitetibl.checklistactividade', verbose_name='Checklist')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_checklist_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetibl.irmao', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Items de Checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
