# Generated by Django 4.2.5 on 2026-09-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0105_checklist_actividade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistactividade',
            options={'ordering': ['departamento__designacao'], 'verbose_name': 'Checklist de Actividade', 'verbose_name_plural': 'Checklists de Actividades'},
        ),
        migrations.AddField(
            model_name='checklistactividade',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='sitetibl.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='checklistactividade',
            name='actividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='sitetibl.actividade', verbose_name='Actividade'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistactividade',
            unique_together={('actividade', 'departamento')},
        ),
    ]
