# Generated by Django 4.2.5 on 2026-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0106_checklist_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistactividade',
            name='dia_activacao',
            field=models.IntegerField(blank=True, help_text='Para semanal: 0=Segunda … 6=Domingo. Para mensal: dia do mês (1-31).', null=True, verbose_name='Dia de Activação'),
        ),
        migrations.AddField(
            model_name='checklistactividade',
            name='hora_notificacao',
            field=models.TimeField(blank=True, help_text='Hora em que os responsáveis recebem a notificação.', null=True, verbose_name='Hora de Notificação'),
        ),
        migrations.AddField(
            model_name='checklistactividade',
            name='notificar_responsaveis',
            field=models.BooleanField(default=True, verbose_name='Notificar responsáveis'),
        ),
        migrations.AddField(
            model_name='checklistactividade',
            name='recorrencia',
            field=models.CharField(choices=[('unica', 'Única'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='unica', max_length=10, verbose_name='Recorrência'),
        ),
        migrations.AddField(
            model_name='checklistactividade',
            name='ultima_geracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última geração automática'),
        ),
    ]
