# Generated by Django 4.2.5 on 2026-09-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0107_checklist_recorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atribuicao', 'Tarefa atribuída'), ('disponivel', 'Checklist disponível'), ('lembrete', 'Lembrete de execução'), ('proxima_prazo', 'Tarefa próxima do prazo'), ('atrasada', 'Tarefa atrasada')], default='disponivel', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='sitetibl.checklistactividade', verbose_name='Checklist')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_checklist', to='sitetibl.irmao', verbose_name='Destinatário')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='sitetibl.itemchecklist', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Notificação de Checklist',
                'verbose_name_plural': 'Notificações de Checklist',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
