# Generated by Django 4.2.5 on 2026-09-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0108_notificacoes_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistactividade',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='sitetibl.departamento', verbose_name='Departamento'),
        ),
    ]
