# Generated by Django 4.2.5 on 2026-09-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetibl', '0109_checklist_dept_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchecklist',
            options={'ordering': ['concluido', 'ordem', 'id'], 'verbose_name': 'Item de Checklist', 'verbose_name_plural': 'Items de Checklist'},
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='dizimooferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes', to='sitetibl.dizimooferta', verbose_name='Dízimo/Oferta gerado'),
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes', to='sitetibl.entrada', verbose_name='Entrada gerada'),
        ),
    ]
